[package]
name = "influxdb3_py_api"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
influxdb3_wal = { path = "../influxdb3_wal" }
influxdb3_catalog = {path = "../influxdb3_catalog"}
influxdb-line-protocol = { workspace = true }
schema = { workspace = true }

[dependencies.pyo3]
version = "0.22.6"
# this is necessary to automatically initialize the Python interpreter
features = ["auto-initialize", "gil-refs"]

[lints]
workspace = true
